version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: trevvos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: trevvos
      POSTGRES_PASSWORD: trevvos
      POSTGRES_DB: trevvos
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
