services:
  - type: web
    name: trevvos-api
    env: node
    plan: starter
    region: oregon
    rootDir: apps/api
    buildCommand: |
      pnpm install --frozen-lockfile
      pnpm --filter @trevvos/api build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
