import {
  Booking,
  Car,
  DashboardMetric,
  RentalRequest,
  UserProfile,
} from './models';

const owner = {
  id: 'owner-1',
  name: 'Marina Oliveira',
  memberSince: '2024',
  rating: 4.9,
  responseTime: 'Responde em até 1 hora',
  avatarInitials: 'MO',
};

export const CARS: Car[] = [
  {
    id: 'onix-premier-2023',
    brand: 'Chevrolet',
    model: 'Onix Premier',
    year: 2023,
    city: 'São Paulo',
    neighborhood: 'Vila Mariana',
    dailyPrice: 189,
    transmission: 'Automático',
    rating: 4.9,
    reviews: 34,
    available: true,
    category: 'Hatch',
    color: 'Azul',
    seats: 5,
    imageClass: 'car-blue',
    description: 'Compacto, confortável e econômico para circular pela cidade ou viajar.',
    features: ['Ar-condicionado', 'Central multimídia', 'Câmera de ré', 'Bluetooth'],
    rules: ['Não fumar no veículo', 'Pets somente com caixa de transporte', 'CNH válida'],
    owner,
  },
  {
    id: 't-cross-comfortline-2024',
    brand: 'Volkswagen',
    model: 'T-Cross Comfortline',
    year: 2024,
    city: 'Curitiba',
    neighborhood: 'Batel',
    dailyPrice: 278,
    transmission: 'Automático',
    rating: 5,
    reviews: 21,
    available: true,
    category: 'SUV',
    color: 'Cinza',
    seats: 5,
    imageClass: 'car-silver',
    description: 'SUV moderno, espaçoso e completo para passeios em família.',
    features: ['Piloto automático', 'Android Auto', 'Apple CarPlay', 'Sensor de estacionamento'],
    rules: ['Não fumar no veículo', 'Limite de 500 km por reserva', 'CNH há mais de 2 anos'],
    owner: { ...owner, id: 'owner-2', name: 'Rafael Souza', avatarInitials: 'RS' },
  },
  {
    id: 'corolla-altis-2022',
    brand: 'Toyota',
    model: 'Corolla Altis',
    year: 2022,
    city: 'Belo Horizonte',
    neighborhood: 'Savassi',
    dailyPrice: 315,
    transmission: 'Automático',
    rating: 4.8,
    reviews: 47,
    available: true,
    category: 'Sedã',
    color: 'Branco',
    seats: 5,
    imageClass: 'car-white',
    description: 'Sedã premium com excelente conforto, segurança e espaço interno.',
    features: ['Bancos em couro', 'Ar digital', 'Controle de estabilidade', 'Chave presencial'],
    rules: ['Não fumar no veículo', 'Uso exclusivamente em vias pavimentadas', 'CNH válida'],
    owner: { ...owner, id: 'owner-3', name: 'Luciana Lima', avatarInitials: 'LL' },
  },
  {
    id: 'renegade-longitude-2023',
    brand: 'Jeep',
    model: 'Renegade Longitude',
    year: 2023,
    city: 'Rio de Janeiro',
    neighborhood: 'Botafogo',
    dailyPrice: 295,
    transmission: 'Automático',
    rating: 4.9,
    reviews: 29,
    available: false,
    category: 'SUV',
    color: 'Verde',
    seats: 5,
    imageClass: 'car-green',
    description: 'SUV robusto e tecnológico, ideal para quem busca conforto e presença.',
    features: ['Central multimídia', 'Ar digital', 'Câmera de ré', 'Controle de tração'],
    rules: ['Não fumar no veículo', 'Sem transporte de cargas', 'CNH há mais de 2 anos'],
    owner,
  },
  {
    id: 'hb20-comfort-2023',
    brand: 'Hyundai',
    model: 'HB20 Comfort',
    year: 2023,
    city: 'Florianópolis',
    neighborhood: 'Centro',
    dailyPrice: 172,
    transmission: 'Manual',
    rating: 4.7,
    reviews: 18,
    available: true,
    category: 'Hatch',
    color: 'Prata',
    seats: 5,
    imageClass: 'car-silver',
    description: 'Prático e econômico, perfeito para compromissos urbanos e fins de semana.',
    features: ['Ar-condicionado', 'Bluetooth', 'Direção elétrica', 'Vidros elétricos'],
    rules: ['Não fumar no veículo', 'Devolver limpo', 'CNH válida'],
    owner,
  },
  {
    id: 'tracker-ltz-2024',
    brand: 'Chevrolet',
    model: 'Tracker LTZ',
    year: 2024,
    city: 'Brasília',
    neighborhood: 'Asa Sul',
    dailyPrice: 289,
    transmission: 'Automático',
    rating: 5,
    reviews: 12,
    available: true,
    category: 'SUV',
    color: 'Vermelho',
    seats: 5,
    imageClass: 'car-red',
    description: 'SUV conectado, seguro e confortável para qualquer roteiro.',
    features: ['Wi-Fi nativo', 'Chave presencial', 'Câmera de ré', 'Alerta de ponto cego'],
    rules: ['Não fumar no veículo', 'Sem uso em estradas não pavimentadas', 'CNH válida'],
    owner,
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: 'B001',
    carId: CARS[1].id,
    carName: `${CARS[1].brand} ${CARS[1].model}`,
    period: '12 a 15 jul. 2026',
    total: 834,
    status: 'Confirmada',
    location: 'Batel, Curitiba',
  },
  {
    id: 'B002',
    carId: CARS[2].id,
    carName: `${CARS[2].brand} ${CARS[2].model}`,
    period: '03 a 05 mai. 2026',
    total: 630,
    status: 'Concluída',
    location: 'Savassi, Belo Horizonte',
  },
  {
    id: 'B003',
    carId: CARS[0].id,
    carName: `${CARS[0].brand} ${CARS[0].model}`,
    period: '21 a 23 ago. 2026',
    total: 567,
    status: 'Aguardando',
    location: 'Vila Mariana, São Paulo',
  },
];

export const REQUESTS: RentalRequest[] = [
  {
    id: 'S001',
    carName: 'Chevrolet Onix Premier',
    renterName: 'João Martins',
    period: '08 a 11 jul. 2026',
    total: 567,
    status: 'Pendente',
  },
  {
    id: 'S002',
    carName: 'Chevrolet Onix Premier',
    renterName: 'Camila Rocha',
    period: '18 a 20 jul. 2026',
    total: 378,
    status: 'Pendente',
  },
  {
    id: 'S003',
    carName: 'Jeep Renegade Longitude',
    renterName: 'André Silva',
    period: '02 a 06 jun. 2026',
    total: 1180,
    status: 'Aprovada',
  },
];

export const DASHBOARD_METRICS: DashboardMetric[] = [
  { label: 'Carros anunciados', value: '2', detail: '1 disponível agora', tone: 'blue' },
  { label: 'Solicitações pendentes', value: '2', detail: 'Aguardando sua resposta', tone: 'orange' },
  { label: 'Receita estimada', value: 'R$ 2.480', detail: 'Neste mês', tone: 'green' },
  { label: 'Taxa de ocupação', value: '68%', detail: '+8% no último mês', tone: 'purple' },
];

export const USER_PROFILE: UserProfile = {
  id: 'user-1',
  name: 'Lucas Almeida',
  email: 'lucas.almeida@email.com',
  phone: '(11) 99999-0000',
  city: 'São Paulo, SP',
};
